version: '3.8'
services:
  # 1. Oracle Database
  splitpay-db:
    image: gvenzl/oracle-xe
    container_name: splitpay-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: splitpay123
    networks:
      - splitpay-net

  # 2. Redis Cache
  splitpay-redis:
    image: redis:alpine
    container_name: splitpay-redis
    ports:
      - "6379:6379"
    networks:
      - splitpay-net

  # 3. Prometheus (The Recorder)
  prometheus:
    image: prom/prometheus
    container_name: splitpay-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - splitpay-net

  # 4. Grafana (The Dashboard)
  grafana:
    image: grafana/grafana
    container_name: splitpay-grafana
    ports:
      - "3000:3000"
    networks:
      - splitpay-net

  # 5. Zookeeper (Manages Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1  # <--- CHANGED from latest
    container_name: splitpay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - splitpay-net

  # 6. Kafka (The Message Broker)
  kafka:
    image: confluentinc/cp-kafka:7.6.1  # <--- CHANGED from latest
    container_name: splitpay-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: splitpay-zookeeper:2181 # Ensure this matches container name
      # INTERNAL: For other docker containers
      # EXTERNAL: For your IntelliJ on localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://splitpay-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - splitpay-net

networks:
  splitpay-net:
    driver: bridge