global:
  scrape_interval: 15s # How often to check the sensors

scrape_configs:
  - job_name: 'splitpay-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']